### ISSUE TITLE
   PRACTICA 1 UNIDAD 3 PROPOSICIONES LÓGICAS

### ISSUE THREAD

**Issue by Victor-noe12** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Victor-noe12#1]
[PROPOSICIONES_LOGICAS.pdf](https://github.com/user-attachments/files/17442482/PROPOSICIONES_LOGICAS.pdf)

**Comment by Berenice1719** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
bien hecho y revisado..
